import { cn } from "@/lib/utils/cn";
import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "@/theme/ThemeRegistry"
import { Toaster } from "@/components/ui/toaster"
import AuthProvider from "@/provider/AuthProvider"
import 'tailwindcss/tailwind.css'
export const metadata: Metadata = {
  title: "Nv Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={cn("bg-white h-full w-full")}>
        <ThemeRegistry>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeRegistry>
        <Toaster />
      </body>
    </html>
  );
}
